name:                Haskem
version:             0.1.0.0
github:              "FabianGD/Haskem"
license:             MIT
author:              "Fabian George Droege"
maintainer:          "fabian.g.droege@gmail.com"
copyright:           "2019 Fabian George Droege"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fabiangd/Haskem#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text
- microlens-platform
- filepath
- utility-ht
- containers
- formatting
- vector
- hmatrix
- extra

library:
  source-dirs: src

executables:
  Haskem-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskem

tests:
  Haskem-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskem
